### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by AlexandreSNeto** [gekowa/node-pd#2] opened 2016-09-16 14:58 UTC
I tried to use this command, but I'm getting this error:

```
$ pd config -u ***@gmail.com -p mypass -s /path/to/download
$ pd download integrating-docker-with-devops-automated-workflows
Logging in with ***@gmail.com
success!
Downloading: 1 of 1 course(s).
Loading course: [integrating-docker-with-devops-automated-workflows]
Course: Integrating Docker with DevOps Automated Workflows
(node:9584) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'log' of undefined
```

My node version:
```
$ node --version
v6.6.0
```

**Comment by gekowa** [comment] 2016-09-26 07:52
This is caused by a stupid typo (console.console.log), which has been fixed in 0.0.10.

**Closed** 2016-09-26 07:52 UTC
